version: '3.1'

services:
  db:
    image: mongo:latest
    container_name: mongodb
    environment:
        - MONGO_INITDB_ROOT_PASSWORD=123456
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_DATABASE=mongodb_test
    ports:
        - "27017:27017"
    volumes:
        - test-mongodb:/data:/data/db

volumes:
    test-mongodb:
